### ISSUE TITLE
FILE regressionDB.csv

### ISSUE THREAD

**Issue by bansaldivy99** [ManuverGujjar/AgroVision#1]
Hey , Can you please tell from where you got file regressionDB.csv

![regressiondb](https://user-images.githubusercontent.com/43462642/111023033-a9e0a080-83fc-11eb-9f90-3dfdd3a4c704.png)

**Comment by ManuverGujjar** [comment]
i think we got it from some gov. site. not sure this part was done by my friend.

**Comment by bansaldivy99** [comment]
It would be great if we can get the source , We were trying to figure out but did not got any clue
If Possible can you please give contact info of the friend i can enquire about this

Your little help can be very helpful for us !
Thanks !

**Comment by ManuverGujjar** [comment]
my friend told me that it is from some youtube channel video which he doesn't remember now.

**Comment by bansaldivy99** [comment]
Ok Thanks !
